collections:
  clubs:
    output: true

plugins:
  - jekyll-paginate
  - jekyll-feed

#Old,deprecated,mostly limited pagination settings.
#paginate: off
#paginate_path: nil

#Jekyll Pagination Settings
#Not supported by Github Pages.
pagination:
  enabled: true
  per_page: 2
  offset: 1
  sort_field: date
  category: posts
